### ISSUE TITLE
500 (Internal Server Error)

### ISSUE THREAD

**Issue by dvdobrovolskiy** [Maxim-us/many-points-on-the-map#1]
load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=5.0.3:4 POST http://somelink.soemsite.ru/wp-admin/admin-ajax.php 500 (Internal Server Error)

**Comment by dvdobrovolskiy** [comment]
2019/01/23 16:08:38 [error] 24813#24813: *3274271 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 6 passed to MXMPOTMDa
taBaseTalk::add_new_map() must be an instance of int, string given, called in /hosting/realgrad.ru/somelink/wp-content/plugins/many-points-on-the-
map/includes/admin/class-database-talk.php on line 49 and defined in /hosting/realgrad.ru/somelink/wp-content/plugins/many-points-on-the-map/inclu
des/admin/class-database-talk.php on line 58" while reading response header from upstream, client: 31.163.84.106, server: somelink.realgrad.ru, re
quest: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php5.6-fpm.sock:", host: "somelink.realgrad.ru", referrer: "ht
tp://somelink.realgrad.ru/wp-admin/admin.php?page=mxmpotm-many-points-on-the-map-add"

**Comment by Maxim-us** [comment]
Скажите, пожалуйста, какую версию плагина Вы используете?
Вы качали с https://wordpress.org/plugins/many-points-on-the-map/ или с Гитхаба?
Если, Вам не трудно, скиньте, пожалуйста версию ПХП вашего сайта и Mysql.
Большое спасибо за Ваше письмо!)

**Comment by dvdobrovolskiy** [comment]
1.0.1
c https://wordpress.org/plugins/many-points-on-the-map/
5.6.40
5.7.24

**Comment by Maxim-us** [comment]
Спасибище!!!!)
Буду фиксить

**Comment by dvdobrovolskiy** [comment]
Та велкам, еще вот такое есть в админке 
![image](https://user-images.githubusercontent.com/7299951/51766598-c9bd8900-20fc-11e9-8151-02d3dea6ff9f.png)


Потестить тут
http://somelink.realgrad.ru/wp-admin
temp
L2C5JeFnas4T$KfqV@zPgDP&

**Comment by Maxim-us** [comment]
Вы золото!!!)

**Comment by Maxim-us** [comment]
JS ошибка не от моего плагина. Она на всех стр. https://snag.gy/vtHY5z.jpg
Рою дальше

**Comment by Maxim-us** [comment]
Готово!) Спасибо большое Вам! http://somelink.realgrad.ru/test-map/

**Comment by dvdobrovolskiy** [comment]
Шикарно, спс!
